version: "3.3"
services:
  aware:
    restart: unless-stopped
    image: sdpequinor/aware:latest
    volumes:
      - ./test-api/:/src
    ports:
      - 5000:5000

  web:
    image: aware-web
    build: .
    volumes:
      - ./src/:/code/src
    ports:
      - 3000:3000
